### ISSUE TITLE
update on Loop

### ISSUE THREAD

**Issue by SamShiSS** [jwalton/etcd3-ts#1]
So Loop's etcd was still having issues after you left, which made me dig into this repo. As it turned out, about a month after you created this etcd client, Microsoft took over the original [Etcd client library](https://github.com/microsoft/etcd3/releases) that Loop was using when we switched from Consul to Etcd. Since then a bunch of things got fixed in recent releases. Now I have switched back to the Microsoft-maintained Etcd client library, and thus removed Loop's dependency on this library.

**Comment by jwalton** [comment]
Good to see that one actually being maintained.  :)  This one can safely fade into obscurity then.
